<a href="https://colab.research.google.com/github/abdirahinosman1/Obesity-Dataset-Data-Preparation/blob/main/obesity_data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd
from google.colab import files
from sklearn.preprocessing import MinMaxScaler

# Upload the CSV file
uploaded = files.upload()

# Load dataset
df = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv')

# Preview dataset
print("First five rows:")
display(df.head())

# --------------------------------------------------
# Step 1: Clean column formats and text formatting
# --------------------------------------------------

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Remove extra spaces from text/categorical columns
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].str.strip()

# --------------------------------------------------
# Step 2: Convert numerical columns to correct formats
# --------------------------------------------------

numeric_cols = [
    'Age',
    'Heigh (M)t',
    'Weight (KG)',
    'BMI',
    'Vegetable Consumption',
    'Number of Main Meals',
    'Water Intake',
    'Physical Activity',
    'Technology Use'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Convert Age to integer after handling missing values later
# Do not convert yet if there are missing values

# --------------------------------------------------
# Step 3: Handle missing values
# --------------------------------------------------

# Replace missing numerical values with the mean of each column
for col in numeric_cols:
    mean_value = np.nanmean(df[col].values)
    df[col] = np.where(np.isnan(df[col]), mean_value, df[col])

# Convert Age to integer after missing values are handled
df['Age'] = df['Age'].round().astype(np.int64)

# --------------------------------------------------
# Step 4: Filter unrealistic outliers
# --------------------------------------------------

# Keep only realistic BMI values
df = df[(df['BMI'] >= 10) & (df['BMI'] <= 80)]

# Keep only realistic Age values
df = df[(df['Age'] >= 0) & (df['Age'] <= 100)]

# Keep only realistic Height values in meters
df = df[(df['Heigh (M)t'] >= 1.0) & (df['Heigh (M)t'] <= 2.5)]

# Keep only realistic Weight values in KG
df = df[(df['Weight (KG)'] >= 20) & (df['Weight (KG)'] <= 250)]

# --------------------------------------------------
# Step 5: Remove duplicate rows
# --------------------------------------------------

duplicate_count = df.duplicated().sum()
print("Duplicate Rows Before Cleaning:", duplicate_count)

df = df.drop_duplicates()

print("Duplicate Rows After Cleaning:", df.duplicated().sum())

# --------------------------------------------------
# Step 6: Calculate descriptive statistics
# --------------------------------------------------

bmi_values = df['BMI'].values
weight_values = df['Weight (KG)'].values
age_values = df['Age'].values

avg_bmi = np.mean(bmi_values)
max_bmi = np.max(bmi_values)
avg_weight = np.mean(weight_values)
avg_age = np.mean(age_values)

print(f"Average BMI: {avg_bmi:.2f}")
print(f"Highest BMI: {max_bmi:.2f}")
print(f"Average Weight: {avg_weight:.2f} kg")
print(f"Average Age: {avg_age:.2f} years")

# --------------------------------------------------
# Step 7: Normalize data WITHOUT replacing original columns
# --------------------------------------------------

cols_to_normalize = ['Age', 'Heigh (M)t', 'Weight (KG)', 'BMI']

scaler = MinMaxScaler()
normalized_values = scaler.fit_transform(df[cols_to_normalize])

df[['Normalized_Age',
    'Normalized_Height',
    'Normalized_Weight',
    'Normalized_BMI']] = normalized_values

print("Normalized columns preview:")
display(df[['Age', 'Heigh (M)t', 'Weight (KG)', 'BMI',
            'Normalized_Age', 'Normalized_Height',
            'Normalized_Weight', 'Normalized_BMI']].head())

# --------------------------------------------------
# Step 8: Create summary table
# --------------------------------------------------

summary_table = df.describe()

print("Summary Table:")
display(summary_table)

# Save summary table
summary_table.to_csv("summary_table.csv")

# --------------------------------------------------
# Step 9: Data quality checks
# --------------------------------------------------

print("Missing Values:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nSummary Statistics:")
display(df.describe())

print("\nUnique Values in Categorical Columns:")
for col in df.select_dtypes(include=['object']).columns:
    print(f"\nUnique values in {col}:")
    print(df[col].unique())

# --------------------------------------------------
# Step 10: Automated data quality report
# --------------------------------------------------

def data_quality_report(df):
    print("Missing Values:\n", df.isnull().sum(), "\n")
    print("Data Types:\n", df.dtypes, "\n")
    print("Duplicate Rows:", df.duplicated().sum(), "\n")
    print("Summary Statistics:\n")
    display(df.describe())

    for col in df.select_dtypes(include=['object']).columns:
        print(f"Unique values in {col}:\n", df[col].unique(), "\n")

data_quality_report(df)

# --------------------------------------------------
# Step 11: Save cleaned dataset
# --------------------------------------------------

df.to_csv("cleaned_obesity_dataset.csv", index=False)

print("Files saved successfully:")
print("cleaned_obesity_dataset.csv")
print("summary_table.csv")

# Download files
files.download("cleaned_obesity_dataset.csv")
files.download("summary_table.csv")

Saving ObesityDataSet_raw_and_data_sinthetic.csv to ObesityDataSet_raw_and_data_sinthetic (10).csv
First five rows:

,Gender,Age,Heigh (M)t,Weight (KG),BMI,Family History,High Calorie Food,Vegetable Consumption,Number of Main Meals,Food Between Meals,SMOKE,Water Intake,Calorie Monitoring,Physical Activity,Technology Use,Alcohol Consumption,Transportation,Obesity Level
0,Female,21,1.62,64.0,24.4,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21,1.52,56.0,24.2,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23,1.80,77.0,23.8,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27,1.80,87.0,26.9,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22,1.78,89.8,28.3,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

Duplicate Rows Before Cleaning: 1
Duplicate Rows After Cleaning: 0
Average BMI: 29.77
Highest BMI: 50.80
Average Weight: 86.85 kg
Average Age: 24.36 years
Normalized columns preview:

,Age,Heigh (M)t,Weight (KG),BMI,Normalized_Age,Normalized_Height,Normalized_Weight,Normalized_BMI
0,21,1.62,64.0,24.4,0.148936,0.320755,0.186567,0.301587
1,21,1.52,56.0,24.2,0.148936,0.132075,0.126866,0.296296
2,23,1.80,77.0,23.8,0.191489,0.660377,0.283582,0.285714
3,27,1.80,87.0,26.9,0.276596,0.660377,0.358209,0.367725
4,22,1.78,89.8,28.3,0.170213,0.622642,0.379104,0.404762

Summary Table:

,Age,Heigh (M)t,Weight (KG),BMI,Vegetable Consumption,Number of Main Meals,Water Intake,Physical Activity,Technology Use,Normalized_Age,Normalized_Height,Normalized_Weight,Normalized_BMI
count,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000
mean,24.357143,1.702593,86.854602,29.765149,2.421668,2.701036,2.004272,1.011859,0.662395,0.220365,0.476591,0.357124,0.443522
std,6.381438,0.093268,26.196468,8.026699,0.534785,0.764770,0.608040,0.852569,0.607594,0.135775,0.175976,0.195496,0.212347
min,14.000000,1.450000,39.000000,13.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,1.630000,66.000000,24.400000,2.000000,2.696759,1.590670,0.123045,0.000000,0.127660,0.339623,0.201493,0.301587
50%,23.000000,1.700000,83.050000,28.900000,2.396772,3.000000,2.000000,1.000000,0.630866,0.191489,0.471698,0.328731,0.420635
75%,26.000000,1.770000,108.000000,36.100000,3.000000,3.000000,2.461422,1.675361,1.000000,0.255319,0.603774,0.514925,0.611111
max,61.000000,1.980000,173.000000,50.800000,3.000000,4.000000,3.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000

Missing Values:
Gender                   0
Age                      0
Heigh (M)t               0
Weight (KG)              0
BMI                      0
Family History           0
High Calorie Food        0
Vegetable Consumption    0
Number of Main Meals     0
Food Between Meals       0
SMOKE                    0
Water Intake             0
Calorie Monitoring       0
Physical Activity        0
Technology Use           0
Alcohol Consumption      0
Transportation           0
Obesity Level            0
Normalized_Age           0
Normalized_Height        0
Normalized_Weight        0
Normalized_BMI           0
dtype: int64

Data Types:
Gender                    object
Age                        int64
Heigh (M)t               float64
Weight (KG)              float64
BMI                      float64
Family History            object
High Calorie Food         object
Vegetable Consumption    float64
Number of Main Meals     float64
Food Between Meals        object
SMOKE                     object
Water Intake             float64
Calorie Monitoring        object
Physical Activity        float64
Technology Use           float64
Alcohol Consumption       object
Transportation            object
Obesity Level             object
Normalized_Age           float64
Normalized_Height        float64
Normalized_Weight        float64
Normalized_BMI           float64
dtype: object

Duplicate Rows:
0

Summary Statistics:

,Age,Heigh (M)t,Weight (KG),BMI,Vegetable Consumption,Number of Main Meals,Water Intake,Physical Activity,Technology Use,Normalized_Age,Normalized_Height,Normalized_Weight,Normalized_BMI
count,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000
mean,24.357143,1.702593,86.854602,29.765149,2.421668,2.701036,2.004272,1.011859,0.662395,0.220365,0.476591,0.357124,0.443522
std,6.381438,0.093268,26.196468,8.026699,0.534785,0.764770,0.608040,0.852569,0.607594,0.135775,0.175976,0.195496,0.212347
min,14.000000,1.450000,39.000000,13.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,1.630000,66.000000,24.400000,2.000000,2.696759,1.590670,0.123045,0.000000,0.127660,0.339623,0.201493,0.301587
50%,23.000000,1.700000,83.050000,28.900000,2.396772,3.000000,2.000000,1.000000,0.630866,0.191489,0.471698,0.328731,0.420635
75%,26.000000,1.770000,108.000000,36.100000,3.000000,3.000000,2.461422,1.675361,1.000000,0.255319,0.603774,0.514925,0.611111
max,61.000000,1.980000,173.000000,50.800000,3.000000,4.000000,3.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000

Unique Values in Categorical Columns:

Unique values in Gender:
['Female' 'Male']

Unique values in Family History:
['yes' 'no']

Unique values in High Calorie Food:
['no' 'yes']

Unique values in Food Between Meals:
['Sometimes' 'Frequently' 'Always' 'no']

Unique values in SMOKE:
['no' 'yes']

Unique values in Calorie Monitoring:
['no' 'yes']

Unique values in Alcohol Consumption:
['no' 'Sometimes' 'Frequently' 'Always']

Unique values in Transportation:
['Public_Transportation' 'Walking' 'Automobile' 'Motorbike' 'Bike']

Unique values in Obesity Level:
['Normal_Weight' 'Overweight_Level_I' 'Overweight_Level_II'
 'Obesity_Type_I' 'Insufficient_Weight' 'Obesity_Type_II'
 'Obesity_Type_III']
Missing Values:
 Gender                   0
Age                      0
Heigh (M)t               0
Weight (KG)              0
BMI                      0
Family History           0
High Calorie Food        0
Vegetable Consumption    0
Number of Main Meals     0
Food Between Meals       0
SMOKE                    0
Water Intake             0
Calorie Monitoring       0
Physical Activity        0
Technology Use           0
Alcohol Consumption      0
Transportation           0
Obesity Level            0
Normalized_Age           0
Normalized_Height        0
Normalized_Weight        0
Normalized_BMI           0
dtype: int64

Data Types:
 Gender                    object
Age                        int64
Heigh (M)t               float64
Weight (KG)              float64
BMI                      float64
Family History            object
High Calorie Food         object
Vegetable Consumption    float64
Number of Main Meals     float64
Food Between Meals        object
SMOKE                     object
Water Intake             float64
Calorie Monitoring        object
Physical Activity        float64
Technology Use           float64
Alcohol Consumption       object
Transportation            object
Obesity Level             object
Normalized_Age           float64
Normalized_Height        float64
Normalized_Weight        float64
Normalized_BMI           float64
dtype: object

Duplicate Rows: 0

Summary Statistics:

,Age,Heigh (M)t,Weight (KG),BMI,Vegetable Consumption,Number of Main Meals,Water Intake,Physical Activity,Technology Use,Normalized_Age,Normalized_Height,Normalized_Weight,Normalized_BMI
count,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000,2086.000000
mean,24.357143,1.702593,86.854602,29.765149,2.421668,2.701036,2.004272,1.011859,0.662395,0.220365,0.476591,0.357124,0.443522
std,6.381438,0.093268,26.196468,8.026699,0.534785,0.764770,0.608040,0.852569,0.607594,0.135775,0.175976,0.195496,0.212347
min,14.000000,1.450000,39.000000,13.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,1.630000,66.000000,24.400000,2.000000,2.696759,1.590670,0.123045,0.000000,0.127660,0.339623,0.201493,0.301587
50%,23.000000,1.700000,83.050000,28.900000,2.396772,3.000000,2.000000,1.000000,0.630866,0.191489,0.471698,0.328731,0.420635
75%,26.000000,1.770000,108.000000,36.100000,3.000000,3.000000,2.461422,1.675361,1.000000,0.255319,0.603774,0.514925,0.611111
max,61.000000,1.980000,173.000000,50.800000,3.000000,4.000000,3.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000

Unique values in Gender:
 ['Female' 'Male']

Unique values in Family History:
 ['yes' 'no']

Unique values in High Calorie Food:
 ['no' 'yes']

Unique values in Food Between Meals:
 ['Sometimes' 'Frequently' 'Always' 'no']

Unique values in SMOKE:
 ['no' 'yes']

Unique values in Calorie Monitoring:
 ['no' 'yes']

Unique values in Alcohol Consumption:
 ['no' 'Sometimes' 'Frequently' 'Always']

Unique values in Transportation:
 ['Public_Transportation' 'Walking' 'Automobile' 'Motorbike' 'Bike']

Unique values in Obesity Level:
 ['Normal_Weight' 'Overweight_Level_I' 'Overweight_Level_II'
 'Obesity_Type_I' 'Insufficient_Weight' 'Obesity_Type_II'
 'Obesity_Type_III']

Files saved successfully:
cleaned_obesity_dataset.csv
summary_table.csv